services:
  # MYSQL DATABASE
  joke_database:
    image: mysql:latest
    volumes:
      # sue /prod id production
      - "./database/mysql/dev:/docker-entrypoint-initdb.d:ro"
      # Add the following line for production:
      # - db_data:/var/lib/mysql
      # Delete in production:
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    networks:
      - sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
    command:
      - --host-cache-size=3
  # ———————————————————— ADMINER —————————————————————————————————————————————
  adminer:
    image: adminer:latest
    #restart: "on-failure"
    networks:
      - sql
      # PROD:
      #- web
      # expose:
      #   - 8080
    ports:
      - "8080:8080"
  # SERVER SIDE RENDERING:
  joke_ssr:
    image: ssr:latest
    build:
      context: ./
      dockerfile: ssr.Dockerfile
    # Delete in production:
    ports:
      - "${SSR_PORT}:${SSR_PORT}"
    expose:
      - "${SSR_PORT}"
    networks:
      - sql
      - web
    env_file:
      - ./environment/.env.development
  # ———————————————————— AUTHENTICATION ——————————————————————————————————————
  joke_auth:
    image: auth:latest
    build:
      context: ./
      dockerfile: auth.Dockerfile
    ports:
      # Delete in production:
      - "${AUTH_PORT}:${AUTH_PORT}"
    expose:
      - "${AUTH_PORT}"
    networks:
      - sql
      - web
    env_file:
      - ./environment/.env.development
  # NGINX:
  joke_webserver:
    image: nginx:stable
    volumes:
      - "./static:/usr/share/nginx/html:ro"
      - "./static/event_handlers:/usr/share/nginx/html/event_handlers:ro"
      - "./RegEx:/usr/share/nginx/RegEx:ro"
      - "./assets:/usr/share/nginx/assets:ro"
      - "./nginx/templates/development:/etc/nginx/templates:ro"
      - "./nginx/config/development/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    networks:
      - web
    env_file:
      - ./environment/.env.development
    # Delete in production
    command: [ nginx-debug, "-g", "daemon off;" ]
#——————————————————— ADMINER —————————————————————————————————————————————————

networks:
  sql:
  web:
    # Uncomment in production:
    #volumes:
    #  db-data:
